name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - uses: dtolnay/rust-toolchain@stable
      - run: |
          sudo pacman -Syu
          sudo pacman -S --needed \
          webkit2gtk \
          base-devel \
          curl \
          wget \
          file \
          openssl \
          appmenu-gtk-module \
          gtk3 \
          libappindicator-gtk3 \
          librsvg \
          libvips

      - run: pnpm i

      - run: pnpm tauri build
